### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by XWJ110826** [yingqichao/fnd-bootstrap#2]
请问可以提供一下预训练模型和处理后的数据集吗？

**Comment by zhangmingdao** [comment]
同问

**Comment by yingqichao** [comment]
等我这阵子手头科研和项目忙好后，会在这个issue下面发数据集和checkpoint的google drive和百度网盘的链接

**Comment by yingqichao** [comment]
各位，久等，数据集在如下链接中，请及时下载。

Gossipcop和Politifact： 
链接：https://pan.baidu.com/s/1zQKDYn6RuvOZrVEqWNpMhQ 
提取码：aaai 

weibo（老版本）：
链接：https://pan.baidu.com/s/13b-NY86_5rOfURd_ivSlyQ 
提取码：aaai 

Weibo-21（根据提供的json自行下载的）：
链接：https://pan.baidu.com/s/1yLhubnORaLTwKr4bWSNaMg 
提取码：aaai 

对应xlsx请根据我在data_preprocess里面提供的脚本进行生成

**Comment by XWJ110826** [comment]
你好，第一个和第三个链接显示“此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！”，能否再提供一次链接，可能是链接的名字有问题

**Comment by yingqichao** [comment]
> 你好，第一个和第三个链接显示“此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！”，能否再提供一次链接，可能是链接的名字有问题

估计再传一次还是这个结果，因为数据集里有些条目带有敏感内容，后续我上传Google Drive链接在这里。

**Comment by yingqichao** [comment]
各位好，我被告知无权自行分发weibo数据集，如暂未通过上面的链接成功下载，请联系数据集作者索要，通过填写申请表的方式。谢谢。

**Comment by XWJ110826** [comment]
你好，您方便说一下具体的实现步骤嘛？

**Comment by XWJ110826** [comment]
您好，由于代码有些多，您能具体说一下实现的步骤吗？帮助排除不需要的代码

**Comment by yanghongqi123** [comment]
> 各位好，我被告知无权自行分发weibo数据集，如暂未通过上面的链接成功下载，请联系数据集作者索要，通过填写申请表的方式。谢谢。



> 各位好，我被告知无权自行分发weibo数据集，如暂未通过上面的链接成功下载，请联系数据集作者索要，通过填写申请表的方式。谢谢。

原作者的申请表被填写次数到上限了，weibo21的数据集可以发我一份吗？非常非常感谢！我的邮箱：1215331584@qq.com

**Comment by REXKEV214** [comment]
> 各位，久等，数据集在如下链接中，请及时下载。
> 
> Gossipcop和Politifact： 链接：https://pan.baidu.com/s/1zQKDYn6RuvOZrVEqWNpMhQ 提取码：aaai
> 
> weibo（老版本）： 链接：https://pan.baidu.com/s/13b-NY86_5rOfURd_ivSlyQ 提取码：aaai
> 
> Weibo-21（根据提供的json自行下载的）： 链接：https://pan.baidu.com/s/1yLhubnORaLTwKr4bWSNaMg 提取码：aaai
> 
> 对应xlsx请根据我在data_preprocess里面提供的脚本进行生成
作者您好，我们最近想根据您的代码复现论文，请问可以提供一下gossipcop的数据集吗，万分感谢！！！我的邮箱：k15257703775@gmail.com

**Comment by REXKEV214** [comment]
> > 你好，第一个和第三个链接显示“此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！”，能否再提供一次链接，可能是链接的名字有问题
> 
> 估计再传一次还是这个结果，因为数据集里有些条目带有敏感内容，后续我上传Google Drive链接在这里。

作者您好，我们最近想根据您的代码复现论文，请问可以提供一下gossipcop的数据集吗，万分感谢！！！我的邮箱：[k15257703775@gmail.com](mailto:k15257703775@gmail.com)

**Comment by yingqichao** [comment]
请大家向GossipCop数据集原作者索要该数据集，不要再向Dr Singhal索要该数据集，感谢配合。我和Dr Singhal都不是原作者，无权分享别人的劳动成果。

**Comment by zihuicai** [comment]
您好，请问能给我发一下weibo和weibo21数据集吗，我发邮件给Dr Qiong Nan没有回。邮箱1936498326@qq.com

**Comment by sbdisnhdkfjabsh** [comment]
> 您好！请问旧版Weibo数据是来源于Multimodal Fusion with Recurrent Neural Networks for Rumor Detection on Microblogs吗？这份数据也是通过Dr Qiong Nan获取吗？当前我在比较不同的方法，但Weibo上不同的事件划分会影响结果，因此想获得您的数据划分
你好，请问您现在拿到旧版weibo数据了吗？

**Comment by sbdisnhdkfjabsh** [comment]
> 您好！请问旧版Weibo数据是来源于Multimodal Fusion with Recurrent Neural Networks for Rumor Detection on Microblogs吗？这份数据也是通过Dr Qiong Nan获取吗？当前我在比较不同的方法，但Weibo上不同的事件划分会影响结果，因此想获得您的数据划分

您好，请问您现在拿到旧版weibo数据了吗？

**Comment by Tan-YiLong** [comment]
您好，请问能给我发一下weibo和weibo21数据集吗，我发邮件给Dr Qiong Nan没有回。邮箱[1694206141@qq.com](mailto:1694206141@qq.com)，谢谢！

**Comment by dxkube** [comment]
我已经毕业了，这些数据集我都没有留，你可以在这里申请数据集 https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__Q4mnQlURFcxUTBYOEZSWEk1SFA2Q1BRRDhaOTRQQi4u




1215331584
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yingqichao/fnd-bootstrap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年6月24日(星期二) 上午9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yingqichao/fnd-bootstrap] 数据集 (Issue #2)



Tan-YiLong left a comment (yingqichao/fnd-bootstrap#2)
 
您好，请问能给我发一下weibo和weibo21数据集吗，我发邮件给Dr Qiong ***@***.***，谢谢！

**Comment by Tan-YiLong** [comment]
好的，谢谢
