### ISSUE TITLE
关于验证集与测试集

### ISSUE THREAD

**Issue by GGDNacl** [yingqichao/fnd-bootstrap#4]
您好，感谢您出色的工作！我注意到您将数据集划分为训练集与测试集，当模型验证时，直接加载了测试集进行验证，而没有单独的测试集，请问论文中的结果是如何得到的？是多次训练对最高的准确率进行平均吗？

**Comment by yingqichao** [comment]
是的，和之前的一系列文章一样（EANN CAFE MCAN等），本文没有设置验证集，直接用不同随机种子训练5次以后取每次最高准确率来做平均。也就是说论文中汇报的准确率实际上是对不同训练下能够取得的最优结果的一个估计。

**Comment by GGDNacl** [comment]
感谢您的回复！
