### ISSUE TITLE
关于twitter数据集

### ISSUE THREAD

**Issue by chenshu2000** [yingqichao/fnd-bootstrap#5]
感谢您的工作！对于在twitter数据集上我有几个问题，首先是在Twitter_dataset.py文件以下两个路径的文件我不知道是如何得到的：
train_path = root_path + '/train_twitters.xlsx
 test_path = root_path+'/test_datasets.xlsx'

然后是process_data_twitter.py中的“Data/twitter-merged/”文件和 path = "/home/groupshare/mae-main/ztrain_en.xlsx"中的文件，

最后请问能不能直接上传root_path中Twitter文件，我想它应该包含我所需要的所有文件，非常感谢！！！

**Comment by yingqichao** [comment]
你好，这项工作没有在Twitter上进行验证，原因是Twitter数据集的图像数量太少。代码里虽然有Twitter相关内容，却实际并未使用。
