### ISSUE TITLE
数据标签

### ISSUE THREAD

**Issue by Tiantian20000321** [yingqichao/fnd-bootstrap#8]
作者你好，我想问一下这篇论文单视图的标签是怎么定ground-truth的，是利用文中说得阈值还是一整条信息的标签。

**Comment by yingqichao** [comment]
单视图标签就直接是整条信息的标签，不同试图训练时候单试图如果特征不够甚至不对的（比如GT是假新闻，但是image pattern这边一点假的也看不出来，不在假的分布里面），那可以看作对于那个试图的脏数据。每个试图都是强行去让网络根据GT去判断哪些是有代表性的特征。

**Comment by lanjianY** [comment]
> 单视图标签就直接是整条信息的标签，不同试图训练时候单试图如果特征不够甚至不对的（比如GT是假新闻，但是image pattern这边一点假的也看不出来，不在假的分布里面），那可以看作对于那个试图的脏数据。每个试图都是强行去让网络根据GT去判断哪些是有代表性的特征。

感谢作者回答，请问./mae_pretrain_vit_base.pth文件是自己去mae去下载ViT.Base吗

**Comment by yingqichao** [comment]
> > 单视图标签就直接是整条信息的标签，不同试图训练时候单试图如果特征不够甚至不对的（比如GT是假新闻，但是image pattern这边一点假的也看不出来，不在假的分布里面），那可以看作对于那个试图的脏数据。每个试图都是强行去让网络根据GT去判断哪些是有代表性的特征。
> 
> 感谢作者回答，请问./mae_pretrain_vit_base.pth文件是自己去mae去下载ViT.Base吗

对的哦，直接用官方的就行
